import os

BOT_TOKEN = os.environ.get("BOT_TOKEN")

DEMO_MODE = False

CHECK_ORDERS_INTERVAL = 2
CHECK_PRICES_INTERVAL  = 30
CHECK_STOCK_INTERVAL   = 60

LOW_STOCK_THRESHOLD = 5

SUPPORT_USERNAME = "@your_username"
